param()

$ErrorActionPreference = "Stop"

$currentPath = (Get-Location).Path
if ((Test-Path (Join-Path $currentPath "AGENTS.md")) -and (Test-Path (Join-Path $currentPath "js\bootstrap\script-manifest.js"))) {
    $repoRoot = $currentPath
} else {
    $repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
}
Set-Location $repoRoot

$manifestPath = Join-Path $repoRoot "js\bootstrap\script-manifest.js"
$manifestSource = [System.IO.File]::ReadAllText($manifestPath)
$manifestMatch = [regex]::Match($manifestSource, "applicationScripts\s*:\s*\[(?<scripts>[\s\S]*?)\]")

if (-not $manifestMatch.Success) {
    throw "No se ha podido leer applicationScripts en js\bootstrap\script-manifest.js."
}

$scriptPaths = [regex]::Matches($manifestMatch.Groups["scripts"].Value, "'([^']+)'") | ForEach-Object {
    $_.Groups[1].Value
}

$outputDir = Join-Path $repoRoot "dist\js"
$outputPath = Join-Path $outputDir "coda.bundle.js"
New-Item -ItemType Directory -Path $outputDir -Force | Out-Null

$parts = New-Object System.Collections.Generic.List[string]
$parts.Add("/* Generated by tools/build-js-bundle.ps1. Do not edit directly. */")
$parts.Add("/* Source manifest: js/bootstrap/script-manifest.js */")

foreach ($scriptPath in $scriptPaths) {
    $absoluteScriptPath = Join-Path $repoRoot $scriptPath

    if (-not (Test-Path $absoluteScriptPath)) {
        throw "No existe el script declarado en el manifest: $scriptPath"
    }

    $parts.Add("")
    $parts.Add("/* Source: $scriptPath */")
    $parts.Add([System.IO.File]::ReadAllText($absoluteScriptPath))
    $parts.Add(";")
}

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($outputPath, ($parts -join "`r`n"), $utf8NoBom)

Write-Host "Bundle generado: dist\js\coda.bundle.js"
